name: Hola Mundo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hola Mundo
        run: echo "Hola Mundo"
      - name: Compile and run js
        run: node index.js